import { getCompetitionStats, listCompetitions, listCompetitionTripRoutes, hasSupabaseConfig } from '../../../lib/supabaseRest';
import { checkRequestRateLimit } from '../../../lib/rateLimit';

// Public data for /demo — the presentation page that shows how a cycling
// competition builds up a picture of where children ride.
//
// SAFETY: this endpoint only ever serves competitions whose name or
// description says "demo" (same rule as the DEMO badge in the app). Those hold
// synthetic, road-following routes generated by staff, never real children's
// trips. Per-trip routes for real competitions stay internal (backoffice only).
const RATE_LIMIT = 60;
const RATE_LIMIT_WINDOW_MS = 5 * 60 * 1000;

function isDemoComp(competition) {
  return /\bdemo\b/i.test(competition?.name || '') || /\bdemo\b/i.test(competition?.description || '');
}

export default async function handler(req, res) {
  if (req.method !== 'GET') {
    res.setHeader('Allow', ['GET']);
    return res.status(405).end('Method Not Allowed');
  }
  const rateLimit = checkRequestRateLimit(req, 'demo-spor', RATE_LIMIT, RATE_LIMIT_WINDOW_MS);
  if (!rateLimit.allowed) {
    res.setHeader('Retry-After', Math.ceil(rateLimit.retryAfterMs / 1000));
    return res.status(429).json({ error: 'For mange forespørsler' });
  }
  if (!hasSupabaseConfig()) return res.status(404).json({ error: 'Ikke konfigurert' });

  try {
    let id = typeof req.query.id === 'string' ? req.query.id : '';
    if (!id) {
      // No id: the newest demo competition, preferring an active one.
      const all = await listCompetitions({ activeOnly: false });
      const demos = all.filter(isDemoComp);
      const pick = demos.find((c) => c.active) || demos[0];
      if (!pick) return res.status(404).json({ error: 'Ingen demo-konkurranse' });
      id = pick.id;
    }
    const mode = req.query.mode === 'sykkel' || req.query.mode === 'gange' ? req.query.mode : null;
    const stats = await getCompetitionStats(id, { mode, includeGeojson: true });
    if (!stats || !isDemoComp(stats.competition)) return res.status(404).json({ error: 'Fant ikke demo-konkurransen' });

    const trips = await listCompetitionTripRoutes(id);
    const colorByClub = new Map(stats.leaderboard.map((row) => [row.club, row.color]));
    const withColor = trips.map((t) => ({ ...t, color: colorByClub.get(t.club) || '#0b5d4d' }));

    res.setHeader('Cache-Control', 's-maxage=120, stale-while-revalidate=600');
    return res.status(200).json({ ...stats, trips: withColor });
  } catch (error) {
    console.error(error);
    return res.status(500).json({ error: 'Kunne ikke hente demo-data' });
  }
}
