import { getCompetitionStats, listCompetitions, listCompetitionTripRoutes, hasSupabaseConfig } from '../../../lib/supabaseRest';
import { checkRequestRateLimit } from '../../../lib/rateLimit';
import { simplifyPath } from '../../../lib/geoPrivacy';
import { buildPaint } from '../../../lib/paintMap';
import venues from '../../../data/demo-venues.json';

// Public data for /demo — the presentation page that shows how a cycling
// competition builds up a picture of where children ride.
//
// SAFETY: this endpoint only ever serves competitions whose name or
// description says "demo" (same rule as the DEMO badge in the app). Those hold
// synthetic, road-following routes generated by staff, never real children's
// trips. Per-trip routes for real competitions stay internal (backoffice only).
const RATE_LIMIT = 60;
const TRIP_LINE_MAX_POINTS = 80;
const HEAT_GRID_M = 30;
const RATE_LIMIT_WINDOW_MS = 5 * 60 * 1000;

// Compact Strava-style heat geometry: snap every route to a ~30 m grid, count
// how many trips use each grid edge, then chain edges of equal weight into
// polylines and emit one MultiLineString per weight. Roughly 20x smaller than
// one Feature per 25 m segment, which matters when 800 routes are on screen.
function buildHeat(trips, gridM = HEAT_GRID_M) {
  const dLat = gridM / 111320;
  const edges = new Map(); // "a|b" -> { a, b, w }
  for (const trip of trips) {
    const seen = new Set();
    let prev = null;
    for (const [lng, lat] of trip.path || []) {
      if (!Number.isFinite(lng) || !Number.isFinite(lat)) continue;
      const dLng = gridM / (111320 * Math.cos((lat * Math.PI) / 180));
      const key = `${Math.round(lat / dLat)},${Math.round(lng / dLng)}`;
      const pt = [Number((Math.round(lng / dLng) * dLng).toFixed(5)), Number((Math.round(lat / dLat) * dLat).toFixed(5))];
      if (prev && prev.key !== key) {
        const ek = prev.key < key ? `${prev.key}|${key}` : `${key}|${prev.key}`;
        if (!seen.has(ek)) {
          seen.add(ek);
          const e = edges.get(ek);
          if (e) e.w += 1;
          else edges.set(ek, { a: prev.key < key ? prev.pt : pt, b: prev.key < key ? pt : prev.pt, ak: prev.key < key ? prev.key : key, bk: prev.key < key ? key : prev.key, w: 1 });
        }
      }
      if (!prev || prev.key !== key) prev = { key, pt };
    }
  }
  // Chain edges per weight into polylines.
  const byWeight = new Map();
  for (const e of edges.values()) {
    if (!byWeight.has(e.w)) byWeight.set(e.w, []);
    byWeight.get(e.w).push(e);
  }
  const features = [];
  for (const [w, list] of byWeight) {
    const at = new Map(); // node key -> edges touching it
    for (const e of list) {
      for (const k of [e.ak, e.bk]) { if (!at.has(k)) at.set(k, []); at.get(k).push(e); }
    }
    const used = new Set();
    const lines = [];
    for (const start of list) {
      if (used.has(start)) continue;
      used.add(start);
      const line = [start.a, start.b];
      let endKey = start.bk;
      for (;;) {
        const next = (at.get(endKey) || []).find((e) => !used.has(e));
        if (!next) break;
        used.add(next);
        if (next.ak === endKey) { line.push(next.b); endKey = next.bk; } else { line.push(next.a); endKey = next.ak; }
        if (line.length > 400) break;
      }
      lines.push(line);
    }
    features.push({ type: 'Feature', properties: { weight: w }, geometry: { type: 'MultiLineString', coordinates: lines } });
  }
  return { type: 'FeatureCollection', features };
}

function isDemoComp(competition) {
  return /\bdemo\b/i.test(competition?.name || '') || /\bdemo\b/i.test(competition?.description || '');
}

export default async function handler(req, res) {
  if (req.method !== 'GET') {
    res.setHeader('Allow', ['GET']);
    return res.status(405).end('Method Not Allowed');
  }
  const rateLimit = checkRequestRateLimit(req, 'demo-spor', RATE_LIMIT, RATE_LIMIT_WINDOW_MS);
  if (!rateLimit.allowed) {
    res.setHeader('Retry-After', Math.ceil(rateLimit.retryAfterMs / 1000));
    return res.status(429).json({ error: 'For mange forespørsler' });
  }
  if (!hasSupabaseConfig()) return res.status(404).json({ error: 'Ikke konfigurert' });

  try {
    let id = typeof req.query.id === 'string' ? req.query.id : '';
    if (!id) {
      // No id: the newest demo competition, preferring an active one.
      const all = await listCompetitions({ activeOnly: false });
      const demos = all.filter(isDemoComp);
      const pick = demos.find((c) => c.active) || demos[0];
      if (!pick) return res.status(404).json({ error: 'Ingen demo-konkurranse' });
      id = pick.id;
    }
    const mode = req.query.mode === 'sykkel' || req.query.mode === 'gange' ? req.query.mode : null;
    const stats = await getCompetitionStats(id, { mode, includeGeojson: false });
    if (!stats || !isDemoComp(stats.competition)) return res.status(404).json({ error: 'Fant ikke demo-konkurransen' });

    const trips = await listCompetitionTripRoutes(id);
    const filtered = mode ? trips.filter((t) => t.mode === mode) : trips;
    const heat = buildHeat(filtered);
    const colorByClub = new Map(stats.leaderboard.map((row) => [row.club, row.color]));
    // «Mal kartet» preview: club-owned roads (>= 2 trips from the club).
    const paint = buildPaint(filtered, { colorFor: (c) => colorByClub.get(c) || '#0b5d4d' });
    // Per-trip lines only need city-scale shape: Douglas-Peucker each route
    // down to a few dozen points so ~800 trips stay a small download. The
    // density geojson above is still built from the full paths.
    const withColor = trips.map((t) => {
      // simplifyPath works on ordered [lng, lat] pairs (same as stored paths).
      const slim = simplifyPath(t.path, { maxPoints: TRIP_LINE_MAX_POINTS }).map(([lng, lat]) => [Number(Number(lng).toFixed(5)), Number(Number(lat).toFixed(5))]);
      return { ...t, path: slim, color: colorByClub.get(t.club) || '#0b5d4d' };
    });

    res.setHeader('Cache-Control', 's-maxage=120, stale-while-revalidate=600');
    const { geojson: _g, ...rest } = stats;
    return res.status(200).json({ ...rest, geojson: heat, trips: withColor, venues, paint: paint.geojson, paintBoard: paint.leaderboard, paintedEdges: paint.paintedEdges });
  } catch (error) {
    console.error(error);
    return res.status(500).json({ error: 'Kunne ikke hente demo-data' });
  }
}
